### ISSUE TITLE
Unable to connect to core mosquitto broker

### ISSUE THREAD

**Issue by dermotos** [yllibed/Zigbee2MqttAssistant#266]
I'm unable to get zigbee2mqttassistant connect to my mqtt broker.

### Log

```
Starting Zigbee2MqttAssistant v0.3.147+Branch.master.Sha.92d831d1df50a48c4a2fd38c201e9465dc7e88dd...
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to connect to MQTT server 192.168.1.25.
```

### Configuration

Tried multiple including:
```yaml
settings:
  mqttserver: addon_core_mosquitto
```

```yaml
settings:
  mqttserver: 192.168.1.25
  mqttport: 1883
```

My Home Assistant mqtt broker is configured as so:

```yaml
mqtt:
  broker: core-mosquitto
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'
```
I do not have a username or password configured on my mqtt broker.

All other software connects to my broker simply via `mqtt://192.168.1.25:1883/` with no other configuration needed (e.g.: username/password)

**Comment by Turiok** [comment]
Hi @dermotos , 

Do you tried :

```yaml
settings:
mqttserver: addon_core_mosquitto
mqttport: 1883
```

What is the error with this configuration?
