### ISSUE TITLE
[BUG]Docker install does not show my devices and says bridge is offline

### ISSUE THREAD

**Issue by YamiFrankc** [yllibed/Zigbee2MqttAssistant#341]
# Describe the bug

## To Reproduce
Run use docker in the same pi as zigbee2mqtt

**Expected behavior**
For it to work

## Steps I took to try resolve the problem
Check settings and docker command:
```
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee
  server: 'mqtt://192.168.1.29:1883'
  user: mqtt
  password: mqtt
advanced:
  log_level: debug
  channel: 20
serial:
  port: /dev/ttyACM0
devices:
 ...
```
` sudo docker run -p 8880:80 -e "Z2MA_SETTINGS__MQTTSERVER=192.168.1.29" -e "Z2MA_SETTINGS__MQTTUSERNAME=mqtt" -e "Z2MA_SETTINGS__MQTTPASSWORD=mqtt" -e "Z2MA_SETTINGS_BASETOPIC=zigbee" --restart unless-stopped carldebilly/zigbee2mqttassistant`

## Screenshots
![image](https://user-images.githubusercontent.com/153349/97064083-392e0a00-1569-11eb-9d30-fd73ff6860c1.png)
