### ISSUE TITLE
Bug after HA last update

### ISSUE THREAD

**Issue by CoolS2** [yllibed/Zigbee2MqttAssistant#366]
**My settings:**

```
settings:
  mqttserver: addon_core_mosquitto
  mqttusername: ****
  mqttpassword: ****
```

**Log:** 

Section 'settings' in configuration does not exists. Will use default settings instead.

**Warn:**

Unable to connect to MQTT server mqtt.
