### ISSUE TITLE
Docker compose

### ISSUE THREAD

**Issue by propositionjoe** [yllibed/Zigbee2MqttAssistant#56]
I'm trying to write a docker compose conf with no sucess,
What missing?

```
   version: '3'
   services:
     zigbee2mqttassistant:
       container_name: zigbee2mqttassistant
       image: carldebilly/zigbee2mqttassistant
       ports:
         - "8880:80"
       restart: always
       environment:
         - Z2MA_SETTINGS__MQTTSERVER=""
         - Z2MA_SETTINGS__MQTTUSERNAME=""
         - Z2MA_SETTINGS__MQTTPASSWORD=""
```

**Comment by carldebilly** [comment]
What kind of error do you have?  I just checked and it's successfully work on my docker installation using this configuration:

``` yml
version: '2'

services:
  zigbee2mqttassistant:
    container_name: zigbee2mqttassistant
    image: carldebilly/zigbee2mqttassistant
    ports:
    - "8880:80"
    restart: always
    environment:
    - Z2MA_SETTINGS__MQTTSERVER="mqtt"
    - Z2MA_SETTINGS__MQTTUSERNAME="mqtt_user"
    - Z2MA_SETTINGS__MQTTPASSWORD="mqtt_pw"
```
