### ISSUE TITLE
Unable to connect to MQTT via Docker

### ISSUE THREAD

**Issue by timdonovanuk** [yllibed/Zigbee2MqttAssistant#68]
This straight up doesn't work in my Docker-compose environment, I see the connection going to my MQTT container, but Mosquitto rejects it:

```
1570614507: New connection from 172.18.0.2 on port 1883.
1570614508: Socket error on client <unknown>, disconnecting.
```

Not sure whether it's not passing username or password or what, correctly. But it doesn't work.

Compose settings:

```
  zigbee2mqtt-assistant:
    container_name: zigbee2mqtt-assistant
    image: carldebilly/zigbee2mqttassistant
    environment:
      - Z2MA_SETTINGS__MQTTSERVER=172.18.0.6
      - Z2MA_SETTINGS__MQTTPORT=1883   
      - Z2MA_SETTINGS__MQTTUSERNAM=myusername
      - Z2MA_SETTINGS__MQTTPASSWORD=mypassword
    ports:
      - 8880:80
    restart: always
```
