### ISSUE TITLE
Permission denied - Unable to start Kestrel

### ISSUE THREAD

**Issue by dakipro** [yllibed/Zigbee2MqttAssistant#91]
Hi,
Thanks for the project. I am trying to run it as a docker container on ubuntu 18 server, using ansible to deploy it. 
My parameters for container are 
```

- name: ensure zigbee2mqttassistant is started
  docker_container:
    name: zigbee2mqttassistant
    image: "carldebilly/zigbee2mqttassistant"
    state: started
    restart_policy: always
    detach: true
    user: "mainuser"
    recreate: yes
    published_ports:
      - "8881:80"
    env:
        Z2MA_SETTINGS__MQTTSERVER: "192.168.1.1"
        Z2MA_SETTINGS__MQTTUSERNAME: "abc"
        Z2MA_SETTINGS__MQTTPASSWORD: "def"
```

However it does not start properly, it complains that 

`
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)

   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)

   at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context)

   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)

   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)

   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)

   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)

   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)

   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)

   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)

   at Zigbee2MqttAssistant.Program.Main(String[] args) in d:\a\1\s\Zigbee2MqttAssistant\Program.cs:line 18

crit: Microsoft.AspNetCore.Server.Kestrel[0]

      Unable to start Kestrel.

System.Net.Sockets.SocketException (13): Permission denied

   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)

   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)

   at System.Net.Sockets.Socket.Bind(EndPoint localEP)

   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()

   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---
`

I tried several combination of paramters, restarting the host, restartint zigbee2mqtt assistant (which has homeassistant to true) etc, but no luck so far. 

As far as I understood the container does not need mapped volume to the host?
Any suggestions where I can start tweaking things around to get it to run?
